language: python
sudo: required
dist: xenial
python:
  - "3.6"
env:
  - ORACLE_HOME=/u01/app/oracle/product/12.1.0.2/db_1 ORACLE_SID=cdb1
# before_install:
#   - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
#   - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh

install:
  - pip install -r requirements.txt
script: 
  - python connect.py

notifications:
  email:
    - acekun141@gmail.com